/***************************************
 * AUTO-GENERATED FILE, DO NOT EDIT!!! *
 * Generated by: tools/config.py       *
 ***************************************/

/* Platform */
#define PLATFORM ppc32
#define PLATFORM_ppc32

/* RAM disk format */
#define RDFMT tmpfs
#define RDFMT_tmpfs

/* Kernel architecture */
#define KARCH ppc32
#define KARCH_ppc32

/* User space architecture */
#define UARCH ppc32
#define UARCH_ppc32

/* Boot architecture */
#define BARCH ppc32
#define BARCH_ppc32

/* Compiler */
#define COMPILER gcc_cross
#define COMPILER_gcc_cross

/* IOMAP dummy support */
#define CONFIG_IOMAP_DUMMY

/* Hierarchical page tables support */
#define CONFIG_PAGE_PT

/* Software integer division support */
#define CONFIG_SOFTINT

/* ASID support */
#define CONFIG_ASID

/* ASID FIFO support */
#define CONFIG_ASID_FIFO

/* OpenFirmware tree support */
#define CONFIG_OFW_TREE

/* FPU support */
#define CONFIG_FPU

/* Lazy FPU context switching */
#define CONFIG_FPU_LAZY

/* Kernel console support */
#define CONFIG_KCONSOLE

/* Input device class */
#define CONFIG_HID_IN generic
#define CONFIG_HID_IN_generic

/* Output device class */
#define CONFIG_HID_OUT generic
#define CONFIG_HID_OUT_generic

/* Support for VIA CUDA controller */
#define CONFIG_VIA_CUDA

/* Macintosh ADB keyboard support */
#define CONFIG_MAC_KBD

/* Framebuffer support */
#define CONFIG_FB

/* OHCI root hub port power switching */
#define OHCI_POWER_SWITCH no
#define OHCI_POWER_SWITCH_no

#define REVISION unknown (unknown)
#define TIMESTAMP_UNIX 1433247968
#define TIMESTAMP 2015-06-02 14:26:08
