# RAM disk format
RDFMT = ext4fs

# Compiler
COMPILER = gcc_cross

# Support for SMP
CONFIG_SMP = y

# Debug build
CONFIG_DEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y
